#' Plot PSI values of a given alternative splicing event
#'
#' Generate a plot of PSI values for a given exon. The PSI values and
#' corresponding quality scores are typically obtained from the
#' \href{https://www.github.com/vastgroup/vast-tools}{vast-tools}
#' pipeline.
#'
#' @details
#' Plots can be customized via the \code{config} option. Either a data frame or
#' the filepath to the config file can be used. Alternatively, plots can be
#' customized using a limited set of graphical parameters as described above.
#'
#' The order of samples (e.g. columns in \emph{x}) as it appears on the
#' resulting plot can be customized using a config file. If a config file is not
#' used and re-ordering is desired, then it must be done manually before calling
#' \code{\link{plot_event}} by altering the columns of \emph{x}.
#'
#' If groups are defined in \code{config} and \code{groupmean=TRUE}, the mean
#' PSI of the samples within each group are drawn as horizontal lines. The
#' colors of the lines are determined by the color set to the first sample of
#' each group by \code{RColorCode} in \code{config}. A corresponding legend key
#' will also be drawn.
#'
#' PSI values that have \emph{NA} value are omitted and not plotted.
#'
#' Error bars based on the confidence interval of the PSI estimation can be
#' shown by setting \code{errorbar=TRUE}.
#'
#' @param x A 1-row data frame containing PSI values to be plotted
#' @param config Optional configuration settings for \code{plot_event}. Can be
#' a path to the \code{.config} file, or 4-column data frame of the \code{.config}
#' file. Use the latter option if you are calling \code{plot_event} multiple times.
#' @param errorbar Logical indicating whether error bars should be drawn
#' @param groupmean Logical indicating whether grouped means should be drawn.
#' Requires \code{config}.
#' @param col Vector of colors with length matching the number of samples. If
#' specificed, this will override the color settings specified in \code{config}.
#' @param title Title of the plot. If \code{NULL} (default), the title generated by \code{\link{make_title}}.
#' @param xlab The x-axis label
#' @param ylab The y-axis label
#' @param ylim Range of y-axis
#' @param cex.main Plot title size (pts)
#' @param cex.yaxis Y-axis font size (pts)
#' @param cex.xaxis X-axis font size (i.e. the sample names) (pts)
#' @param pch Point symbol
#' @param cex.pch Size of datapoints
#' @param gridlines Logical indicating whether grid lines should be drawn
#' @param plot (deprecated) prints the plot
#' @return ggplot2 object
#' @seealso
#' \code{\link{format_table}} for performing some initial conversion steps of \code{x}
#' \code{\link{preprocess_sample_colors}} for pre-processing of \code{x} using
#' \code{config}
#'
#' @export
#' @import methods
#' @import ggplot2
#' @importFrom reshape2 melt
#' @examples
#' \dontrun{
#' plot_event(psi[1,])
#'
#' # Plot with custom configuration
#' config
#' plot_event(psi[1,], config = config, groupmean=TRUE)
#' plot_event(psi[1,], config = "/path/to/config")
#'
#' # Plot using custom configuration, changing point sympol, and y-axis
#' # scale
#' plot_event(psi[1,], config = config, pch = 9, ylim = c(20, 80))
#' }
plot_event <- function(
  x, config = NULL, errorbar = TRUE,
  groupmean = ifelse(is.null(config), FALSE, TRUE), col = NULL,
  title = NULL, xlab = "", ylab = "PSI", ylim = c(0,100),
  cex.main = 14, cex.yaxis = 12, cex.xaxis = 12,
  pch = 20, cex.pch = 3, plot = NULL, gridlines = TRUE) {

  if (!missing(plot)) {
    warning("The option 'plot' has been deprecated")
  }

  if (nrow(x) != 1) {
    stop("Too many rows!")
  }

  # Format input
  x <- format_table(x)
  reordered <- preprocess_sample_colors(x, config, col = col)
  psi <- reordered$data

  if (all(is.na(psi))) {
    warning("Did not find any points to plot")
  }

  N <- ifelse(is.null(ncol(psi)), 1, ncol(psi))
  if (N < 2) {
    stop("Need two or more samples!")
  }

  # Set plot title
  if (is.null(title)) {
    title <- make_title(rownames(x))
  }

  mdata <- suppressMessages(melt(psi,
                                 measure.vars = names(psi),
                                 variable.name = "SampleName"))

  if (errorbar) {
    ci <- as.data.frame(get_beta_ci(reordered$qual))
    ci[which(is.na(psi)),] <- NA
    colnames(ci) <- c("lo", "hi")
    mdata <- cbind(mdata, ci)
  }

  gp <- ggplot(mdata, aes(x = SampleName, y = value)) +
    geom_point(colour = reordered$col, size=cex.pch, shape = pch) +
    ylab("PSI") +
    xlab("") +
    ylim(ylim) +
    ggtitle(title) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = cex.xaxis),
          axis.text.y = element_text(size = cex.yaxis),
          axis.title.y = element_text(size = cex.yaxis),
          title = element_text(size = cex.main))

  # Draw error bars
  if (errorbar) {
    gp <- gp + geom_errorbar(aes(ymin = lo, ymax = hi),
                             colour = reordered$col,
                             width = 0.05)
  }

  # Draw horizontal lines for groups
  if (!is.null(config) && groupmean) {
#     mdata <- join(mdata, reordered$config)
#     msum <- ddply(mdata, .(GroupName), summarize,
#                   mu = mean(value, na.rm=TRUE))
#     gp <- gp + geom_hline(data = msum,
#                           aes(yintercept = mu, colour = GroupName),
#                           show.legend = TRUE) +
#       scale_colour_manual("", values = reordered$group.col)
    gp <- draw_group_means(gp, mdata, reordered$config, reordered$group.col)
  }

  gp <- gp + theme_bw() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = cex.xaxis),
          axis.text.y = element_text(size = cex.yaxis),
          axis.title.y = element_text(size = cex.yaxis),
          title = element_text(size = cex.main))

  if (!gridlines) {
    gp <- gp + theme(panel.grid = element_blank())
  }

  return(gp)
}

#' Make plot title
#'
#' Create a plot title using the event ID
#'
#' @param x A character containing the event ID like
#' "\code{S|TSPAN6|chrX:99885756-99885863|108}"
#' @return A character with a human-friendly title with
#' event type, gene symbol, event coordinates, and length
#' @export
#' @examples
#' f <- format_table(psi)
#' print(make_title(rownames(f)[1]))
make_title <- function(x) {
  event <- strsplit(x, split = "\\|")[[1]]
  sprintf("%s\n(%s, %s bp, type %s)",
                   event[2], event[3], event[4], event[1])
}

#' Make plot title (version 2)
#'
#' Create a plot title using the event ID. Returns symbol and event ID.
#'
#' @param gene A vector or character string
#' @param event A vector or character string with same size as \code{gene}
#' @return A character with a human-friendly title with format:
#' \code{GENE (EVENT ID)}
#' @export
#' @examples
#' print(make_title.2(psi$GENE, psi$EVENT))
make_title.2 <- function(gene, event) {
  sprintf("%s (%s)", gene, event)
}


