#' Produce PSI plots based on output from vast-tools
#'
#' \code{psiplot} is an R package for generating plots of percent spliced-in (PSI)
#' values of alternatively spliced exons. It requires input from
#' \href{https://www.github.com/vastgroup/vast-tools}{vast-tools}, an RNA-Seq
#' pipeline for alternative splicing analysis.
#'
#' @details
#' This package uses input data generated by vast-tools. A sample dataset
#' (\code{psi} and \code{crpkm}) and sample configuration file
#' (\code{config}) is provided.
#'
#' The main function to generate plots is \code{\link{plot_event}} and
#' \code{\link{plot_expr}} for PSI and cRPKM values, respectively.
#'
#' Report bugs and issues to \url{https://github.com/kcha/psiplot/issues}.
#'
#' @name psiplot
#' @docType package
#' @seealso \url{https://www.github.com/kcha/psiplot}
#' @seealso \url{https://www.github.com/vastgroup/vast-tools}
#' @examples
#' library(psiplot)
#' plot_event(psi[1,])
#' plot_event(psi[1,], config=config)
#' plot_expr(crpkm[1,])
#' plot_expr(crpkm[1,], config=config)

NULL
